version: '3'


services:
  
  redis:
    image: redis:6-alpine
    container_name: portfolio-redis

  postgres:
    image: postgres:13-alpine
    container_name: portfolio-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}

  nginx:
    image: mikechurvis/portfolio:nginx-latest
    container_name: portfolio-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_files:/var/www/html/static
      - ~/portfolio/letsencrypt:/etc/letsencrypt
      - /var/www/letsencrypt:/var/www/letsencrypt
    depends_on:
      - django
      - flower
  
  django: &django
    image: mikechurvis/portfolio:django-latest
    container_name: portfolio-django
    env_file:
      - .env
    volumes:
      - static_files:/usr/src/portfolio/staticfiles
    command: [
      gunicorn, portfolio.wsgi:application,
      --bind, 0.0.0.0:8000,
      --timeout, '90',
      --workers, '3',
      --worker-class, gevent,
      --log-level, debug
    ]
    depends_on: 
      - redis
      - postgres

  celery:
    <<: *django
    container_name: portfolio-celery
    command: [
      celery, -A, portfolio, 
      worker, --loglevel=info, --logfile=logs/celery.log
    ]
    depends_on:
      - django

  flower:
    <<: *django
    container_name: portfolio-flower
    command: [
      celery, -A, portfolio,
      "--broker=${CELERY_BROKER}",
      flower, --port=5555
    ]
    depends_on:
      - celery


volumes:
  postgres_data:
  static_files:
