version: '3'

services:
  postgres:
    env_file: 
      - .env
  
  nginx:
    container_name: portfolio-nginx
    build: ./portfolio-nginx
    ports:
      - 9000:9000
    volumes:
      - static_files:/var/www/portfolio/static
    depends_on:
      - django
      - flower
  
  django:
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    ports: []
    expose:
      - 8000
    env_file:
      - .env
    environment: []
    volumes:
      - static_files:/var/www/portfolio/static

volumes:
  postgres_data:
  static_files:
