# Generated by Django 3.2.10 on 2022-01-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0004_message_email_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
