# Generated by Django 3.2.12 on 2022-03-18 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0006_auto_20220202_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=320, validators=[django.core.validators.RegexValidator(message='Please enter a valid email address.', regex='^([a-zA-Z0-9_+-]+.)*[a-zA-Z0-9_+-]+@([a-zA-Z0-9-]+.)+[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=160),
        ),
    ]
