version: '3'

services:
  redis:
    image: redis:alpine

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  django:
    image: mikechurvis/portfolio:latest
    volumes:
      - ~/portfolio/.secrets:/portfolio/.secrets
      - ~/portfolio/logs:/portfolio/logs
      - ~/portfolio/staticfiles:/portfolio/staticfiles
    command: [
      gunicorn, PortfolioAPI.wsgi:application,
      --bind, 0.0.0.0:8000,
      --timeout, '90',
      --workers, '3',
      --worker-class, gevent,
      --log-level, debug
    ]
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ~/portfolio/staticfiles:/var/www/html/static:ro
      - ~/portfolio/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ~/portfolio/certbot/www:/var/www/certbot:ro
      - ~/portfolio/certbot/conf:/etc/nginx/ssl/:ro
    depends_on:
      - django

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ~/portfolio/certbot/www:/var/www/certbot:rw
      - ~/portfolio/certbot/conf:/etc/letsencrypt:rw
      - ~/portfolio/certbot/logs:/var/log/letsencrypt:rw

volumes:
  postgres_data:
