version: '3'

services:
  redis:
    image: redis:alpine

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT

  django:
    image: mikechurvis/portfolio:latest
    volumes:
      - ~/portfolio/.secrets:/portfolio/.secrets
      - ~/portfolio/logs:/portfolio/logs
      - ~/portfolio/staticfiles:/portfolio/staticfiles
    command: [
      gunicorn, PortfolioAPI.wsgi:application,
      --bind, 0.0.0.0:8000,
      --timeout, '90',
      --workers, '3',
      --worker-class, gevent,
      --log-level, debug
    ]
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      - postgres
      - redis

  nginx:
    image: mikechurvis/portfolio:nginx-latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/portfolio/staticfiles:/var/www/html
      - ~/portfolio/letsencrypt:/etc/letsencrypt
      - ~/portfolio/letsencrypt-static:/var/www/letsencrypt
    depends_on:
      - django

volumes:
  postgres_data:
