# Generated by Django 4.0.4 on 2022-05-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('organization', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=320)),
                ('message', models.CharField(max_length=1000)),
                ('datetime_received', models.DateTimeField(auto_now_add=True)),
                ('site_admin_notified_by_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contactformentry',
            constraint=models.CheckConstraint(check=models.Q(('name__length__lte', 120)), name='CHECK__ContactFormEntry__name__length_LTE_120'),
        ),
        migrations.AddConstraint(
            model_name='contactformentry',
            constraint=models.CheckConstraint(check=models.Q(('organization__length__lte', 180)), name='CHECK__ContactFormEntry__organization__length_LTE_180'),
        ),
        migrations.AddConstraint(
            model_name='contactformentry',
            constraint=models.CheckConstraint(check=models.Q(('email__length__lte', 320)), name='CHECK__ContactFormEntry__email__length_LTE_320'),
        ),
        migrations.AddConstraint(
            model_name='contactformentry',
            constraint=models.CheckConstraint(check=models.Q(('message__length__gte', 20)), name='CHECK__ContactFormEntry__message__length_GTE_20'),
        ),
        migrations.AddConstraint(
            model_name='contactformentry',
            constraint=models.CheckConstraint(check=models.Q(('message__length__lte', 1000)), name='CHECK__ContactFormEntry__message__length_LTE_1000'),
        ),
    ]
