# Generated by Django 4.0.4 on 2022-05-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0002_alter_contactformentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformentry',
            options={'ordering': ['datetime_received'], 'verbose_name': 'Contact Form Entry', 'verbose_name_plural': 'Contact Form Entries'},
        ),
    ]
