# Generated by Django 4.0.4 on 2022-05-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0005_contactformentry_check__contactformentry__name__length_gt_0'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contactformentry',
            constraint=models.CheckConstraint(check=models.Q(('email__length__gt', 0)), name='CHECK__ContactFormEntry__email__length_GT_0'),
        ),
    ]
