# Generated by Django 4.0.4 on 2022-06-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0009_remove_contactformentry_check__contactformentry__email__length_lte_320_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddConstraint(
            model_name='emailuser',
            constraint=models.UniqueConstraint(fields=('email_address',), name='UNIQUE__EmailUser__email_address'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='blind_carbon_copies',
            field=models.ManyToManyField(blank=True, related_name='bcc_of', to='ContactForm.emailuser'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='carbon_copies',
            field=models.ManyToManyField(blank=True, related_name='cc_of', to='ContactForm.emailuser'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='recipients',
            field=models.ManyToManyField(related_name='recipient_of', to='ContactForm.emailuser'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_of', to='ContactForm.emailuser'),
        ),
        migrations.AddConstraint(
            model_name='emailconfig',
            constraint=models.UniqueConstraint(fields=('slug',), name='UNIQUE__EmailConfig__slug'),
        ),
    ]
