# Generated by Django 4.0.4 on 2022-06-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0010_emailconfig_emailuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfig',
        ),
        migrations.DeleteModel(
            name='EmailUser',
        ),
    ]
