# Generated by Django 4.0.4 on 2022-06-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0011_delete_emailconfig_delete_emailuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformentry',
            name='admin_notification_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
