# Generated by Django 3.2.9 on 2021-12-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0003_alter_message_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_status',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
