# Generated by Django 3.2.10 on 2022-02-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0005_rename_message_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='company',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='message',
            name='email_status',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
