# Generated by Django 4.0.4 on 2022-06-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_of', to='Emailer.emailuser'),
        ),
    ]
