# Generated by Django 3.2.4 on 2021-11-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sent_at'], name='ContactForm_sent_at_a9fe2d_idx'),
        ),
    ]
