name: Deploy Frontend Client to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy-client-to-gh-pages.yml'
      - 'client/**'
      - '!**.md'

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: client
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.7

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          CONTACT_FORM_API_ROOT_URL: https://backend.mikechurvis.com

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist