name: Deploy Portfolio
on: 
  push:
    branches:
      - release
jobs:
  deploy-backend:
    name: Deploy the portfolio website backend.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print the current working directory to the build console.
        run: pwd && ls -a
      - name: Copy the backend files onto remote server.
        env:
          HOST: ${{ secrets.DROPLET_IP }}
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        uses: appleboy/scp-action@master
        with:
          source: backend/*
          target: ~/portfolio/
          overwrite: true
      - name: Build images, run containers.
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.DROPLET_IP }}
          script: |
            cd ~/portfolio/backend
            source make-env.production.sh ../env
            docker compose \
            -f docker-compose.yml \
            -f docker-compose.production.yml \
            --env-file .env \
            up --build --detach