name: Execute Full Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy-backend.yml'
      - 'api-v2/*'
      - '!**.md'


jobs:
  deploy-backend:
    name: Deploy the portfolio website backend.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the release branch working tree.
        uses: actions/checkout@v2

      - name: Stop the old container network.
          uses: fifsky/ssh-action@master
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            user: ${{ secrets.SSH_USER }}
            host: ${{ secrets.DROPLET_IP }}
            command: |
              cd ~/portfolio
              docker compose down
              rm docker-compose.yml

      - name: Copy the backend files onto remote server.
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.DROPLET_IP }}
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: api-v2/docker-compose.yaml
          target: ~/portfolio
          overwrite: true

      - name: Pull images, run containers.
        uses: fifsky/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.DROPLET_IP }}
          command: |
            cd ~/portfolio
            docker compose pull
            docker compose up --detach