name: Refresh Gmail API auth token every 4 months

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */4 *"

jobs:
  renew-certs:
    name: Renew Gmail API refresh token.
    runs-on: ubuntu-latest
    steps:
      - name: Invoke the token renewal admin command.
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.DROPLET_IP }}
          script: |
            cd ~/portfolio
            docker compose exec -T django bash -c "source venv/bin/activate && python manage.py refreshapitoken"
