name: Renew API Certificates every 2 months

on:
  schedule:
    - cron: "0 0 1 */2 *"

jobs:
  renew-certs:
    name: Renew API Certificates
    runs-on: ubuntu-latest
    steps:
      - name: Invoke the certbot container as a one-off command, then restart Nginx.
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.DROPLET_IP }}
          script: |
            cd ~/portfolio
            docker compose run --rm certbot renew
            docker compose restart nginx